#include <gtest/gtest.h>

#include <numeric>

#include "Common/Exceptions.hpp"
#include "Import/Inflate.hpp"
#include "Utils/Text.hpp"

using namespace ad;

namespace
{

std::string AsString(const std::vector<uint8_t> &v) { return {v.begin(), v.end()}; }

} // namespace

TEST(InflateTest, StoredBlock)
{
    // BFINAL=1, BTYPE=00, LEN=5, NLEN=~5, "hello"
    const std::vector<uint8_t> data{0x01, 0x05, 0x00, 0xFA, 0xFF, 'h', 'e', 'l', 'l', 'o'};
    EXPECT_EQ(AsString(Inflate(data)), "hello");
}

TEST(InflateTest, FixedHuffman)
{
    // zlib.compressobj(9, DEFLATED, -15) of "hello hello hello world"
    EXPECT_EQ(AsString(Inflate(Base64Decode("y0jNyclXyEAiy/OLclIA"))), "hello hello hello world");
}

TEST(InflateTest, DynamicHuffman)
{
    // 300 random words, raw deflate with a dynamic Huffman block (generated by Python zlib)
    const auto out = Inflate(Base64Decode(
        "jVXhesIwCHyVvlrMss1PZzVN3efbT3twCdDt259aUzjggEs7fpV5bdNbaumQljLV0upjKrXOdVpKvR9zmT5SK9/pMR3qfCr1aXJby9J43ASjluU6X54Y6tfm6zHT"
        "/PlcS8BEPDz1DJbdAv6wUX/mIjGtL/LHM6TFg+FlhLaJangJSKJyyp/qObBnqWEEtTZYyI/OwYkvMEReyranZ1lzLssSUULZwHlP5/Mh5RNZGlku93JpDEVTQqCzP"
        "FdDVCkt2CBYnKaHY9/hXZY6/BZNgygSP6uXm4T9+WFCtkQeu8rsZIAqBQZCh9dmAXjDkUZrFF9C2JzINNB47lZR/4ICWpFsk69WoV/1F85uWfBXwjiq1RHkoFLY"
        "s0AJFSZk2BTXrp68WUPUj7hhmGAySoihPbBGANdf7SHCAIO2VJqXpZPAXT6kVGFENPD1BemGfecBX0YRs2rExL3+OV2SxMTLqbtmH8av77dvl5bo6nfjIteGzlc"
        "YgrE5aKxRQr9Qva17t0QQsKjh9lKgQ+jArzeYX51I978vQ7e5OrrmBuritJUk4+gRgyx7xfPj/8cLQoRJZN1OqKxk+GHUr4Ec2xU/fmHIaLDNC8XXTMcoWlYM"
        "fwA="));
    ASSERT_EQ(out.size(), 2259U);
    EXPECT_TRUE(AsString(out).starts_with("timeout database retry error service gat"));
    EXPECT_EQ(std::accumulate(out.begin(), out.end(), 0U) % 65536U, 24081U);
}

TEST(InflateTest, Zlib)
{
    EXPECT_EQ(AsString(InflateZlib(Base64Decode("eJyryslMUihIrMzJT0wBAB7KBLw="))), "zlib payload");
    EXPECT_THROW(InflateZlib(std::vector<uint8_t>{0x00, 0x00}), ParseError);
}

TEST(InflateTest, CorruptInput)
{
    EXPECT_THROW(Inflate(std::vector<uint8_t>{}), ParseError);
    EXPECT_THROW(Inflate(std::vector<uint8_t>{0x07}), ParseError);                              // block type 3
    EXPECT_THROW(Inflate(std::vector<uint8_t>{0x01, 0x05, 0x00, 0x00, 0x00, 'x'}), ParseError); // bad NLEN
    EXPECT_THROW(Inflate(Base64Decode("y0jNyclXyEAiy/OLclIA"), 5), ParseError);                 // size limit
}
