# Smoke test: Mermaid through the command line.
#  - export the sample to .md (flowchart + sequence) and .mmd (sequence);
#  - with MERMAID_IMPORT: convert the .md back to .json and compare names, nodes and messages.
# Parameters: APP, INPUT, OUT_DIR, MERMAID_IMPORT (ON / OFF)
file(REMOVE_RECURSE "${OUT_DIR}/mermaid")
file(MAKE_DIRECTORY "${OUT_DIR}/mermaid")
set(md "${OUT_DIR}/mermaid/sample.md")
set(mmd "${OUT_DIR}/mermaid/sample.mmd")
set(back "${OUT_DIR}/mermaid/back.json")

function(run)
    execute_process(COMMAND "${APP}" ${ARGN} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "${ARGN} failed (rc=${rc})\nstdout: ${out}\nstderr: ${err}")
    endif()
endfunction()

run(--export "${md}" "${INPUT}")
run(--export "${mmd}" --mermaid sequence "${INPUT}")
file(READ "${md}" md_text)
file(READ "${mmd}" mmd_text)
foreach(needle "```mermaid\n---\ntitle:" "flowchart LR" "%% ad:pos svcA" "```mermaid\nsequenceDiagram")
    string(FIND "${md_text}" "${needle}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "${md} lacks ${needle}:\n${md_text}")
    endif()
endforeach()
string(FIND "${mmd_text}" "sequenceDiagram" pos)
if(NOT pos EQUAL 0)
    message(FATAL_ERROR "${mmd} is not a sequence diagram:\n${mmd_text}")
endif()

if(MERMAID_IMPORT)
    run(--convert "${back}" "${md}")
    file(READ "${INPUT}" a)
    file(READ "${back}" b)
    string(JSON name_a GET "${a}" meta name)
    string(JSON name_b GET "${b}" meta name)
    string(JSON nodes_a LENGTH "${a}" nodes)
    string(JSON nodes_b LENGTH "${b}" nodes)
    if(NOT name_a STREQUAL name_b OR NOT nodes_a EQUAL nodes_b)
        message(FATAL_ERROR "round trip changed the document: '${name_a}'/${nodes_a} nodes -> '${name_b}'/${nodes_b} nodes")
    endif()
    string(JSON steps_b LENGTH "${b}" scenario steps)
    if(steps_b LESS 5)
        message(FATAL_ERROR "the scenario was not imported (${steps_b} steps)")
    endif()
endif()
